version: "3"
services:
  api:
    container_name: dev_api
    ports:
      - 3000:3000
    environment:
      - DB_NAME=sportsquizz
      - DB_CONNECTION=mongodb://sportsquizzjd:sqjd@db:27017
    depends_on:
      - db
    command: bash -c "npm install && npm run start"
  db:
    container_name: dev_db
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sportsquizzjd
      - MONGO_INITDB_DATABASE=sportsquizz
      - MONGO_INITDB_ROOT_PASSWORD=sqjd
volumes:
  dbdata:
networks:
  default:
    name: app_dev
